//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum DirectoryEnum {
	Unknown = 0,
	Camera = 1,
	Tv = 2,
	Tv_Staging = 3
}
