//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum RemoteCommandEnum {
	Restart = 0,
	SetSeek = 1,
	VideoInfo = 2
}
