//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { DirectoryEnum } from './model.enum';

export interface IConvertDirectory
{
	converts: IConvertFile[];
}
export interface IConvertFile
{
	id: number;
	directoryEnum: DirectoryEnum;
	output: string | null;
	errored: boolean;
	originalFile: IFile;
	convertedFile: IFile;
	audioStreamNumber: number;
	createdDate: Date;
	startedDate: Date | null;
	endedDate: Date | null;
	queueIndex: number;
}
export interface ICreateDirectoryConvert
{
	converts: ICreateFileConvert[];
}
export interface ICreateFileConvert
{
	directoryEnum: DirectoryEnum;
	originalFile: IFile;
	convertedFile: IFile;
	audioStreamNumber: number;
}
export interface IDir
{
	path: string;
	name: string;
	fullPath: string;
}
export interface IDirectoryInfo
{
	friendlyName: string;
	canPlayVideo: boolean;
	canConvertVideo: boolean;
	canThumbnailVideo: boolean;
	adminViewOnly: boolean;
	dirEnum: DirectoryEnum;
}
export interface IDirsAndFiles
{
	dirs: IDir[];
	files: IFile[];
}
export interface IFile
{
	path: string;
	file: string;
	fullPath: string;
	fileWOExt: string;
	fileExt: string;
	isConvertQueued: boolean;
}
export interface IMetadata
{
	output: string;
	error: string;
}
export interface IString
{
	data: string;
}
export interface IThumbnailError
{
	id: number;
	timesFailed: number;
	directoryEnum: DirectoryEnum;
	error: string;
	file: IFile;
	lastError: Date;
}
export interface IUserProfile
{
	id: number;
	name: string;
}
export interface IRemote
{
	profile: string;
	fromChannel: number;
	toChannel: number | null;
}
export interface IRemoteMoveSeek
{
	seek: number;
	profile: string;
	fromChannel: number;
	toChannel: number | null;
}
export interface IRemoteSetSeek
{
	seekPercent: number;
	profile: string;
	fromChannel: number;
	toChannel: number | null;
}
export interface IRemoteSetVolume
{
	volume: number;
	profile: string;
	fromChannel: number;
	toChannel: number | null;
}
export interface IRemoteVideoInfo
{
	directoryEnum: DirectoryEnum;
	friendlyName: string;
	path: string;
	file: IFile;
	currentTimeSeconds: number;
	maxTimeSeconds: number;
	volume: number;
	isPlaying: boolean;
	profile: string;
	fromChannel: number;
	toChannel: number | null;
}
export interface IAppLogFilter
{
	logLevel: number | null;
	eventId: number | null;
	eventName: string | null;
	minDate: Date | null;
	maxDate: Date | null;
}
export interface ICronLogFilter
{
	name: string | null;
	cronLogType: number | null;
	isCanceled: boolean | null;
	minDate: Date | null;
	maxDate: Date | null;
}
